/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VPSPlanInput = IDL.Record({
  'id' : IDL.Text,
  'ram' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'cores' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const Time = IDL.Int;
export const Submission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const VPSPlan = IDL.Record({
  'id' : IDL.Text,
  'ram' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'cores' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const ContactFormInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addVPSPlan' : IDL.Func([VPSPlanInput], [IDL.Text], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteVPSPlan' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getVPSPlans' : IDL.Func([], [IDL.Vec(VPSPlan)], ['query']),
  'submitContactForm' : IDL.Func([ContactFormInput], [], []),
  'updateVPSPlan' : IDL.Func([IDL.Text, VPSPlan], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VPSPlanInput = IDL.Record({
    'id' : IDL.Text,
    'ram' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'cores' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Submission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const VPSPlan = IDL.Record({
    'id' : IDL.Text,
    'ram' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'cores' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ContactFormInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addVPSPlan' : IDL.Func([VPSPlanInput], [IDL.Text], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteVPSPlan' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getVPSPlans' : IDL.Func([], [IDL.Vec(VPSPlan)], ['query']),
    'submitContactForm' : IDL.Func([ContactFormInput], [], []),
    'updateVPSPlan' : IDL.Func([IDL.Text, VPSPlan], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };