/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactFormInput {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface FAQ { 'question' : string, 'answer' : string }
export interface HostingPlan {
  'features' : Array<string>,
  'name' : string,
  'description' : string,
  'price' : number,
  'planType' : HostingPlanType,
}
export type HostingPlanType = { 'vps' : null } |
  { 'cloud' : null } |
  { 'sharedPlan' : null } |
  { 'dedicated' : null };
export interface Submission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Testimonial {
  'name' : string,
  'quote' : string,
  'company' : string,
  'rating' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'addFAQ' : ActorMethod<[FAQ], undefined>,
  'addHostingPlan' : ActorMethod<[HostingPlan], undefined>,
  'addTestimonial' : ActorMethod<[Testimonial], undefined>,
  'getAllSubmissions' : ActorMethod<[], Array<Submission>>,
  'getFAQs' : ActorMethod<[], Array<FAQ>>,
  'getHostingPlans' : ActorMethod<[], Array<HostingPlan>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'submitContactForm' : ActorMethod<[ContactFormInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];