/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
export const HostingPlanType = IDL.Variant({
  'vps' : IDL.Null,
  'cloud' : IDL.Null,
  'sharedPlan' : IDL.Null,
  'dedicated' : IDL.Null,
});
export const HostingPlan = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Float64,
  'planType' : HostingPlanType,
});
export const Testimonial = IDL.Record({
  'name' : IDL.Text,
  'quote' : IDL.Text,
  'company' : IDL.Text,
  'rating' : IDL.Nat8,
});
export const Time = IDL.Int;
export const Submission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const ContactFormInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFAQ' : IDL.Func([FAQ], [], []),
  'addHostingPlan' : IDL.Func([HostingPlan], [], []),
  'addTestimonial' : IDL.Func([Testimonial], [], []),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
  'getHostingPlans' : IDL.Func([], [IDL.Vec(HostingPlan)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'submitContactForm' : IDL.Func([ContactFormInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FAQ = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
  const HostingPlanType = IDL.Variant({
    'vps' : IDL.Null,
    'cloud' : IDL.Null,
    'sharedPlan' : IDL.Null,
    'dedicated' : IDL.Null,
  });
  const HostingPlan = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Float64,
    'planType' : HostingPlanType,
  });
  const Testimonial = IDL.Record({
    'name' : IDL.Text,
    'quote' : IDL.Text,
    'company' : IDL.Text,
    'rating' : IDL.Nat8,
  });
  const Time = IDL.Int;
  const Submission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const ContactFormInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addFAQ' : IDL.Func([FAQ], [], []),
    'addHostingPlan' : IDL.Func([HostingPlan], [], []),
    'addTestimonial' : IDL.Func([Testimonial], [], []),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getFAQs' : IDL.Func([], [IDL.Vec(FAQ)], ['query']),
    'getHostingPlans' : IDL.Func([], [IDL.Vec(HostingPlan)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'submitContactForm' : IDL.Func([ContactFormInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };