/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FAQ {
    question: string;
    answer: string;
}
export type Time = bigint;
export interface HostingPlan {
    features: Array<string>;
    name: string;
    description: string;
    price: number;
    planType: HostingPlanType;
}
export interface Submission {
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}
export interface ContactFormInput {
    name: string;
    email: string;
    message: string;
}
export interface Testimonial {
    name: string;
    quote: string;
    company: string;
    rating: number;
}
export enum HostingPlanType {
    vps = "vps",
    cloud = "cloud",
    sharedPlan = "sharedPlan",
    dedicated = "dedicated"
}
export interface backendInterface {
    addFAQ(faq: FAQ): Promise<void>;
    addHostingPlan(plan: HostingPlan): Promise<void>;
    addTestimonial(testimonial: Testimonial): Promise<void>;
    getAllSubmissions(): Promise<Array<Submission>>;
    getFAQs(): Promise<Array<FAQ>>;
    getHostingPlans(): Promise<Array<HostingPlan>>;
    getTestimonials(): Promise<Array<Testimonial>>;
    submitContactForm(input: ContactFormInput): Promise<void>;
}
import type { HostingPlan as _HostingPlan, HostingPlanType as _HostingPlanType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFAQ(arg0: FAQ): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFAQ(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFAQ(arg0);
            return result;
        }
    }
    async addHostingPlan(arg0: HostingPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHostingPlan(to_candid_HostingPlan_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHostingPlan(to_candid_HostingPlan_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTestimonial(arg0: Testimonial): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTestimonial(arg0);
            return result;
        }
    }
    async getAllSubmissions(): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissions();
            return result;
        }
    }
    async getFAQs(): Promise<Array<FAQ>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFAQs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFAQs();
            return result;
        }
    }
    async getHostingPlans(): Promise<Array<HostingPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHostingPlans();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHostingPlans();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonials();
            return result;
        }
    }
    async submitContactForm(arg0: ContactFormInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0);
            return result;
        }
    }
}
function from_candid_HostingPlanType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HostingPlanType): HostingPlanType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_HostingPlan_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HostingPlan): HostingPlan {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    features: Array<string>;
    name: string;
    description: string;
    price: number;
    planType: _HostingPlanType;
}): {
    features: Array<string>;
    name: string;
    description: string;
    price: number;
    planType: HostingPlanType;
} {
    return {
        features: value.features,
        name: value.name,
        description: value.description,
        price: value.price,
        planType: from_candid_HostingPlanType_n8(_uploadFile, _downloadFile, value.planType)
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vps: null;
} | {
    cloud: null;
} | {
    sharedPlan: null;
} | {
    dedicated: null;
}): HostingPlanType {
    return "vps" in value ? HostingPlanType.vps : "cloud" in value ? HostingPlanType.cloud : "sharedPlan" in value ? HostingPlanType.sharedPlan : "dedicated" in value ? HostingPlanType.dedicated : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HostingPlan>): Array<HostingPlan> {
    return value.map((x)=>from_candid_HostingPlan_n6(_uploadFile, _downloadFile, x));
}
function to_candid_HostingPlanType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HostingPlanType): _HostingPlanType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_HostingPlan_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HostingPlan): _HostingPlan {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    features: Array<string>;
    name: string;
    description: string;
    price: number;
    planType: HostingPlanType;
}): {
    features: Array<string>;
    name: string;
    description: string;
    price: number;
    planType: _HostingPlanType;
} {
    return {
        features: value.features,
        name: value.name,
        description: value.description,
        price: value.price,
        planType: to_candid_HostingPlanType_n3(_uploadFile, _downloadFile, value.planType)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HostingPlanType): {
    vps: null;
} | {
    cloud: null;
} | {
    sharedPlan: null;
} | {
    dedicated: null;
} {
    return value == HostingPlanType.vps ? {
        vps: null
    } : value == HostingPlanType.cloud ? {
        cloud: null
    } : value == HostingPlanType.sharedPlan ? {
        sharedPlan: null
    } : value == HostingPlanType.dedicated ? {
        dedicated: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
